---
title: input-rangeslider
name: input-rangeslider
collection: atoms
notes: |
  ##### Usage : `input-rangeslider`
---
<div class="input-rangeslider input-rangeslider-container">
  <div class="input-rangeslider-label">Entreprise/Tiers</div>
  <div class="input-rangeslider-range" data-start=0 data-min=0 data-max=100 data-input="input-rangeslider-value-1"></div>
  <input type="text" class="input-rangeslider-value" name="input-rangeslider-value-1" value="">
</div>
