---
title: input-file
name: input-file
collection: atoms
notes: |
  ##### Usage : `input-file`
  ##### Options :
---
<div class="form-group">
  <div class="form-file">
    <div class="label">Certificat de salaire</div>
    <div class="form-file-handler btn btn-lg btn-primary">
      <label for="inputID">Télécharger votre fichier</label>
      <input class="" id="inputID" type="file"></input>
    </div>
  </div>
</div>
