---
title: menu-toggle
name: Menu-toggle
collection: atoms
notes: |
  ##### Usage : `menu-toggle`
---
<a href="#" class="menu-toggle visible-xs visible-sm visible-md">
  <button class="hamburger hamburger--collapse" type="button" aria-label="Menu" aria-controls="navigation">
    <span class="hamburger-box">
      <span class="hamburger-inner"></span>
    </span>
  </button>
  <label>Menu</span>
</a>
