---
title: alert-language
name: alert-language
collection: molecules
notes: |
  ##### Usage : `alert-language`
  ##### Options :
  - **option** - Type
---
<div class="alert alert-info alert-dismissible" role="alert">
  <div class="close pull-right" data-dismiss="alert" aria-label="Close"></div>
  <h4 class="fine-weight">
  Die SAWI ist in zwei Regionen tätig :  Westschweiz (Sitz im Lausanne), Deutschschweiz (Sitz im Zürich). Sie befinden sich jetzt auf dem Westschweiz-Portal. Sie können auf <a href="#" class="">Deutschschweiz</a> klicken um au das Deutschschweiz-Portal zuzugreifen.
  </h4>
</div>
