---
title: alert-language
name: alert-language
collection: molecules
notes: |
  ##### Usage : `alert-language`
  ##### Options :
  - **option** - Type
---
<div class="alert alert-info" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  Die SAWI ist in zwei Regionen tätig :  Westschweiz (Sitz im Lausanne), Deutschschweiz (Sitz im Zürich). Sie befinden sich jetzt auf dem Westschweiz-Portal. Sie können auf <a href="#" class="alert-link">Deutschschweiz</a> klicken um au das Deutschschweiz-Portal zuzugreifen.
</div>