---
title: breadcrumb
name: breadcrumb
collection: molecules
notes: |
  ##### Usage : `breadcrumb`
---
<nav class="breadcrumb" role="breadcrumb" aria-label="Vous êtes ici:">
  <h1 class="hidden" aria-level="3">Vous êtes sur ce chemin.</h1>
  <ul class="list-inline list-no-style list-no-padding">
    <li class="" aria-label="Niveau 1"><a href="#" class="h6">Niveau 1</a></li>
    <li class="" aria-label=">"><i class="fa fa-angle-right" aria-hidden="true"></i></li>
    <li class="" aria-label="Niveau 2"><a href="#" class="h6">Niveau 2</a></li>
    <li class="" aria-label=">"><i class="fa fa-angle-right" aria-hidden="true"></i></li>
    <li class="h6" aria-label="Page">Page</li>
  </ul>
</nav>
