---
title: certifications
name: certifications
collection: molecules
notes: |
  ##### Usage : `certifications`
---
<div class="certifications">
  <a  href="http://www.eduqua.ch" target="blank" class="logo-eduqua">
    <img class="img-responsive" src="/build/img/certification-EDUQUA.png" alt="Certification EDUQUA">
  </a>
  <a href="http://www.eduqua.ch" target="blank" class="logo-sqs">
    <img class="img-responsive" src="/build/img/certification-SQS.png" alt="Certification SQS">
  </a>
  <a href="http://www.eduqua.ch" target="blank" class="logo-iaa">
    <img class="img-responsive" src="/build/img/certification-IAA.png" alt="Certification IAA">
  </a>
</div>
