---
title: certifications
name: certifications
collection: molecules
notes: |
  ##### Usage : `certifications`
---

<div class="spacer spacer-md hidden-md hidden-lg"></div>
<div class="certifications">
  <div class="logo-eduqua">
    <img class="" src="/build/img/certification-EDUQUA.png" alt="Certification EDUQUA">
  </div>
  <div class="logo-sqs">
    <img class="" src="/build/img/certification-SQS.png" alt="Certification SQS">
  </div>
  <div class="logo-iaa">
    <img class="" src="/build/img/certification-IAA.png" alt="Certification IAA">
  </div>
</div>
