---
title: collapse
name: collapse
collection: molecules
notes: |
  ##### Usage : `collapse`
---
<div class="collapse-group">
  <a class="collapse-link">Formations</a>
  <a class="collapse-toggle collapsed btn btn-icon btn-grey" role="button" data-toggle="collapse" href="#collapseFormations" aria-expanded="false" aria-controls="collapseFormations">
    <span class="collapse-chevron sawi-icons sawi-icons-chevron"></span>
    <span class="sr-only">Ouvrir le menu déroulant formations</span>
  </a>
</div>
<div class="collapse" id="collapseFormations">
  <ul class="list-unstyled">
    <li><a href="#">Formations en un clin d'oeil</a></li>
    <li><a href="#">Formations continues</a></li>
    <li><a href="#">Formations à plein temps</a></li>
    <li><a href="#">Speed Learning</a></li>
    <li><a href="#">Formations à la carte</a></li>
  </ul>
</div>
