---
title: contact
name: contact
collection: molecules
notes: |
  ##### Usage : `contact`
  ##### Options :
  - **option** - Type
---
<div class="contact">
  <img src="/build/img/logo.svg" alt="SAWI" class="contact-logo" onerror="this.onerror=null; this.src='/build/img/logo.png'">
  <address class="m-0">
    <h4 class="fine-weight m-0">Academy for Marketing and Communication SA</h4>
    <h4 class="fine-weight m-0">Avenue de Florimont 1, 1006 Lausanne</h4>
  </address>
  <h1 class="m-0 m-t-1"><a href="tel:+41213434060">+41 (0) 21 343 40 60</a></h1>
  <h1 class="m-0"><a href="#">lausanne@sawi.com</a></h1>
  <h4 class="fine-weight m-0 m-t-1">Vous avez encore un fax en 2016,</h4>
  <h4 class="fine-weight m-0">nous aussi : <a href="tel:+41213434061">+41 (0) 21 343 40 61</a></h4>
</div>
