---
title: contact
name: contact
collection: molecules
notes: |
  ##### Usage : `contact`
  ##### Options :
  - **option** - Type
---
<div class="contact">
  <div class="contact-wrapper-logo">
   <img src="/build/img/logo.svg" alt="SAWI" class="contact-logo" onerror="this.onerror=null; this.src='/build/img/logo.png'">
  </div>
  <div class="contact-info">
    <address class="m-0">
      <p class="m-0">Avenue de Florimont 1, 1006 Lausanne</p>
    </address>
    <h3 class="media-heading m-t-1"><a href="#">lausanne@sawi.com</a></h3>
    <h1 class="media-heading"><a href="tel:+41213434060">+41 21 343 40 60</a></h1>
  </div>

  {% include '../molecules/social.html.swig' %}
</div>
