---
title: contact
name: contact
collection: molecules
notes: |
  ##### Usage : `contact`
  ##### Options :
  - **option** - Type
---
<h5>SAWI</h5>
<p>Academy for Marketing and Communication SA</p>
<p><a href="#">Avenue de Florimont 1, 1006 Lausanne</a></p>
<h3><a href="#">+41 (0) 21 343 40 60</a></h3>
<h3><a href="#">lausanne@sawi.com</a></h3>
<p>Vous avez encore un fax en 2016,</p>
<p>nous aussi : <a href="#">+41 (0) 21 343 40 61</a></p>