---
title: dropdown
name: dropdown
collection: molecules
notes: |
  ##### Usage : `dropdown`
---
<div class="dropdown btn-group">
  <button type="button" class="btn btn-underline text-bold">Formations</button>
  <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="dropdown-chevron sawi-icons sawi-icons-chevron"></span>
    <span class="sr-only">Ouvrir le menu déroulant formations</span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#">Formations en un clin d'oeil</a></li>
    <li><a href="#">Formations continues</a></li>
    <li><a href="#">Formations à plein temps</a></li>
    <li><a href="#">Speed Learning</a></li>
    <li><a href="#">Formations à la carte</a></li>
  </ul>
</div>
