---
title: Media-profil
name: media-profil
collection: molecules
---
<div class="media profil-detail">
  <div class="media-left">
    <a href="#">
      <img class="media-object img-circle" src="https://placeholdit.imgix.net/~text?w=250&h=250" alt="In malesuada">
    </a>
  </div>
  <div class="media-body">
    <p class="media-heading">
      <p>Cras et scelerisque ipsum. Pellentesque ut cursus libero, in rhoncus lorem. Phasellus quis lacus consectetur, pellentesque lorem et, efficitur sapien. Duis tincidunt augue at nibh ultrices dictum vel quis metus. Maecenas sollicitudin tempor diam, eget lobortis justo ultrices nec. Ut malesuada bibendum leo, sit amet bibendum lorem. Quisque id turpis nec massa varius rutrum in eget orci. Proin dignissim odio dictum, eleifend eros vel, congue mauris. Integer pulvinar quam nunc, ac efficitur justo molestie quis. Mauris lobortis luctus dolor sit amet cursus. Nullam quis turpis sit amet sapien vestibulum semper et nec purus.</p>
    </p>
  </div>
</div>
