---
title: menu-secondary
name: menu-secondary
collection: molecules
notes: |
  ##### Usage : `menu-secondary`
  ##### Options :
  - **option** - Type
---
<nav class="menu-secondary">
  <ul class="list-unstyled">
    <li><a class="no-underline" href="#">Webcampus SAWI</a></li>
    <li><a class="no-underline" href="#">Recherche <img src="/build/img/search.svg" class="inline-icon"> </a></li>
  </ul>
</nav>
