---
title: menu-desktop
name: menu-desktop
collection: molecules
notes: |
  ##### Usage : `menu-desktop`
---
<div class="menu-desktop">

<div class="dropdown btn-group">
  <a href="#" class="btn btn-link dropdown-link active">Formations</a>
  <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="dropdown-chevron sawi-icons sawi-icons-chevron"></span>
    <span class="sr-only">Ouvrir le menu déroulant formations</span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#">Formations en un clin d'oeil</a></li>
    <li><a href="#">Formations continues</a></li>
    <li><a href="#">Formations à plein temps</a></li>
    <li><a href="#">Speed Learning</a></li>
    <li><a href="#">Formations à la carte</a></li>
  </ul>
</div>

<div class="dropdown">
  <a href="#" class="btn btn-link dropdown-link">Séance d'information</a>
</div>

<div class="dropdown">
  <a href="#" class="btn btn-link dropdown-link">Diplômes</a>
</div>

<div class="dropdown">
  <a href="#" class="btn btn-link dropdown-link">Avec et pour les entreprises</a>
</div>

<div class="dropdown">
  <a href="#" class="btn btn-link dropdown-link">SAWI</a>
</div>

<div class="dropdown">
  <a href="#" class="btn btn-link dropdown-link">Contact</a>
</div>

</div>
