---
title: menu-access
name: menu-access
collection: molecules
notes: |
  Accessible nav with access-key for accessibility purposes.
---
<nav class="menu-access">
  <ul>
    <li><a class="btn btn-primary" href="/" accesskey="1">Page d'accueil du site Sawi</a></li>
    <li><a class="btn btn-primary" href="#main-content" accesskey="2" >Passer la navigation</a></li>
    <li><a class="btn btn-primary" href="#main-navigation" accesskey="3" >Accéder à la navigation</a></li>
    <li><a class="btn btn-primary" href="#search-box" accesskey="4" >Accéder au champ de recherche</a></li>
    <li><a class="btn btn-primary" href="mailto:lausanne@sawi.com" accesskey="9">Contacter nous</a></li>
  </ul>
</nav>
