---
title: newsletter
name: newsletter
collection: molecules
notes: |
  ##### Usage : `newsletter`
  ##### Options :
  - **option** - Type
---
<div class="spacer spacer-md"></div>
<div class="newsletter">
  <h3 class="h1 m-0">La newsletter</h3>
  <h4 class="m-t-0 m-b-0 text-uppercase">Restons en contact</h4>
  <form class="form-inline">
    <div class="spacer spacer-sm hidden-sm hidden-md hidden-lg"></div>
    <div class="form-group m-0">
      <label for="newsletter-email" class="sr-only">Votre adresse email</label>
      <input type="email" size="40" class="form-control full-width form-small" id="newsletter-email" placeholder="jane.doe@example.com">
    </div>
    <div class="form-group m-0">
      <input type="submit" class="btn btn-small btn-blue" id="newsletter-submit" value="J'en suis !">
    </div>
  </form>
</div>
<div class="spacer spacer-sm"></div>
