---
title: newsletter
name: newsletter
collection: molecules
notes: |
  ##### Usage : `newsletter`
  ##### Options :
  - **option** - Type
---
<h2 class="h1 m-0">La newsletter,</h2>
<h2 class="fine-weight m-0">pour ne manquer<br />aucune de nos actualités</h2>
<div class="spacer spacer-md"></div>
<form class="form-inline">
  <div class="form-group">
    <label for="newsletter-email" class="sr-only">Votre adresse email</label>
    <input type="email" size="40" class="form-control full-width" id="newsletter-email" placeholder="jane.doe@example.com">
  </div>
  <div class="form-group">
    <input type="submit" class="btn btn-lg btn-primary" id="newsletter-submit" value="J'en suis !">
  </div>
</form>
