---
title: school-hub
name: school-hub
collection: molecules
notes: |
  ##### Usage : `school-hub`
---
<div class="school-hub">
  <h3 class="m-0 text-uppercase">Swiss Marketing Hub & Schools</h3>
  <div class="spacer spacer-md hidden-lg"></div>
  <div class="schools-logos">
    <a href="#" target="_blank" class="school-sawi">
      <img src="/build/svg/logo-sawi.svg" alt="SAWI">
    </a>

    <a href="#" target="_blank" class="school-supdeluxe">
      <img src="/build/svg/logo-supdeluxe.svg" alt="Sup de Luxe">
    </a>

    <a href="#" target="_blank" class="school-sms">
      <img src="/build/svg/logo-sms.svg" alt="SMS">
    </a>

    <a href="#" target="_blank" class="school-arc">
      <img src="/build/svg/logo-arc.svg" alt="Arc">
    </a>

    <a href="#" target="_blank" class="school-procom">
      <img src="/build/svg/logo-procom-black.svg" alt="Procom">
    </a>

    <a href="#" target="_blank" class="school-polycom">
      <img src="/build/svg/logo-polycom.svg" alt="Polycom">
    </a>
  </div>
</div>
