---
title: search
name: search
collection: molecules
notes: |
  ##### Usage : `search`
  ##### Options :
  - **option** - Type
---
<div id="search" class="search open">
  <form class="search-form">
    <input class="search-input" type="search" placeholder="Search...">
    <button class="search-submit" type="submit"><i class="sawi-icons sawi-icons-search"></i></button>
  </form>
  <span class="search-close"></span>
</div>
