---
title: search-box
name: Search-box
collection: molecules
notes: |
  ##### Usage : `search-box`
---

<div id="search-box" name="search-box" class="search-box">
  <a href="#" class="search-toggle"><i class="sawi-icons sawi-icons-search"></i></a>
</div>
<div class="search-box-modal">
  <a href="" class="close"></a>
  <div class="container">
    <div class="row">
      <div class="spacer spacer-lg"></div>
      <div class="col-md-9 col-xs-9">
        <input class="form-control" type="text" placeholder="Votre recherche">
      </div>
      <div class="col-md-3 col-xs-9 text-xs-left text-right">
        <input class="btn btn-lg" type="submit" value="Rechercher">
      </div>
    </div>
    <div class="spacer spacer-xs"></div>
    <hr>
    <div class="row">
      <div class="col-md-4 fade-in">
        <h5>Nos intervenants</h5>
        <ul>
          <li><a href="#">Denis Le Roussel</a></li>
          <li><a href="#">Jérôme du Fernandes</a></li>
          <li><a href="#">Guy Boucher</a></li>
          <li><a href="#">Margaret-Céline Launay</a></li>
          <li><a href="#">Grégoire Le Barbe</a></li>
        </ul>
      </div>
      <div class="col-md-4 fade-in">
        <h5>Nos cours</h5>
        <ul>
          <li><a href="#">Ullam</a></li>
          <li><a href="#">Necessitatibus occaecati</a></li>
          <li><a href="#">Atque doloribus nam numquam</a></li>
          <li><a href="#">Dignissimos architecto explicabo</a></li>
          <li><a href="#">autem illo quis.</a></li>
        </ul>
      </div>
      <div class="col-md-4 fade-in">
        <h5>Les séances d'informations</h5>
        <ul>
          <li><a href="#">Atque doloribus nam numquam</a></li>
          <li><a href="#">Dignissimos architecto explicabo</a></li>
          <li><a href="#">Ab temporibus fugiat corporis</a></li>
          <li><a href="#">Molestiae voluptatem iste.</a></li>
          <li><a href="#">Inventore iure cumque nulla qui nihil rerum.</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="spacer spacer-lg"></div>
</div>
