---
title: social
name: social
collection: molecules
notes: |
  ##### Usage : `social`
  ##### Options :
  - **option** - Type
---
<div class="social">
  <h2 class="h1 m-0">Social Club </h2>
  <h2 class="fine-weight m-0">Deluxe</h2>
  <ul>
    <li>
      <div class="icon-text icon-text-center">
        <div class="icon" aria-hidden="true">
          <a href="#" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        </div>
        <div class="text">
          <a href="#" target="_blank" class="no-underline">Likez-nous "a lot" sur Facebook</a>
        </div>
      </div>
    </li>

    <li>
      <div class="icon-text icon-text-center">
        <div class="icon" aria-hidden="true">
          <a href="#" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        </div>
        <div class="text">
          <a href="#" target="_blank" class="no-underline">Attrapez nos gazouillis sur Twitter</a>
        </div>
      </div>
    </li>

    <li>
      <div class="icon-text icon-text-center">
        <div class="icon" aria-hidden="true">
          <a href="#" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a>
        </div>
        <div class="text">
          <a href="#" target="_blank" class="no-underline">Jouez-nous en boucle sur Youtube</a>
        </div>
      </div>
    </li>

    <li>
      <div class="icon-text icon-text-center">
        <div class="icon" aria-hidden="true">
          <a href="#" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
        </div>
        <div class="text">
          <a href="#" target="_blank" class="no-underline">Réseautez avec nous sur Linkedin</a>
        </div>
      </div>
    </li>

      <li>
        <div class="icon-text icon-text-center">
          <div class="icon" aria-hidden="true">
            <a href="#" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
          </div>
          <div class="text">
            <a href="#" target="_blank" class="no-underline">Mattez avec nous sur Instagam</a>
          </div>
        </div>
      </li>

  </ul>
</div>
