---
title: social
name: social
collection: molecules
notes: |
  ##### Usage : `social`
  ##### Options :
  - **option** - Type
---
<h3>SAWI</h3>
<h3 class="fine-weight">Social Club Deluxe</h3>
<ul>
	<li><a href="">Likez-nous "a lot" sur Facebook</a></li>
	<li><a href="">Attrapez nos gazouillis sur Twitter</a></li>
	<li><a href="">Jouez-nous en boucle sur Youtube</a></li>
	<li><a href="">Réseautez avec nous sur Linkedin</a></li>
	<li><a href="">Mattez avec nous sur Instagam</a></li>
</ul>