---
title: socials-icons
name: socials-icons
collection: molecules
notes: |
  ##### Usage : `socials-icons`
---
<ul class="socials-icons">
	<li><a target="_blank" href=""><i class="fa fa-snapchat-ghost" aria-hidden="true"></i></a></li>
  <li><a target="_blank" href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
  <li><a target="_blank" href=""><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
  <li><a target="_blank" href=""><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
  <li><a target="_blank" href=""><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
  <li><a target="_blank" href=""><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
</ul>
