---
title: social
name: social
collection: molecules
notes: |
  ##### Usage : `social`
  ##### Options :
  - **option** - Type
---
<div class="contact-social">
  <ul>
    <li class="social-box">
      <a href="#" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    </li>

    <li class="social-box">
      <a href="#" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </li>

    <li class="social-box">
      <a href="#" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a>
    </li>

    <li class="social-box">
      <a href="#" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
    </li>

    <li class="social-box">
      <a href="#" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    </li>

    <li class="social-box social-box-borderless"></li>

  </ul>
</div>
