---
title: teaser-seance
name: teaser-seance
collection: molecules
notes: |
  ##### Usage : `teaser-seance`
  ##### Options :
  - **seance** - object
---
<a href="#" class="teaser-seance no-underline d-block">
  <h5 class="teaser-seance-course media-heading">Spécialiste en stratégie digitale</h5>

  <div class="spacer spacer-xs"></div>
  <div class="teaser-seance-infos">
    <div class="icon-text text-center icon-text-center icon-text-sm">
      <div class="icon" aria-hidden="true">
        <span><i class="fa fa-map-marker" aria-hidden="true"></i></span>
      </div>
      <div class="text">
        <span>Lausanne</span>
      </div>
    </div>
    <div class="icon-text icon-text-center icon-text-sm">
      <div class="icon" aria-hidden="true">
        <span><i class="fa fa-calendar" aria-hidden="true"></i></span>
      </div>
      <div class="text">
        <span class="no-underline">10.09.2016 à 16h00</span>
      </div>
    </div>
  </div>
</a>
