---
title: teaser-seance
name: teaser-seance
collection: molecules
notes: |
  ##### Usage : `teaser-seance`
  ##### Options :
  - **seance** - object
---
<div class="teaser-seance">
  <h5 class="teaser-seance-course media-heading">Spécialiste en stratégie digitale</h5>

  <div class="spacer spacer-sm"></div>
  <div class="teaser-seance-infos">
    <div class="icon-text icon-text-center icon-text-sm">
      <div class="icon" aria-hidden="true">
        <a href="#" target="_blank"><i class="fa fa-map-marker" aria-hidden="true"></i></a>
      </div>
      <div class="text">
        <a href="#" class="no-underline" target="_blank">Lausanne</a>
      </div>
    </div>
    <div class="icon-text icon-text-center icon-text-sm">
      <div class="icon" aria-hidden="true">
        <a href="#" target="_blank"><i class="fa fa-calendar" aria-hidden="true"></i></a>
      </div>
      <div class="text">
        <a href="#" class="no-underline" target="_blank">10.09.2016 à 16h00</a>
      </div>
    </div>
  </div>
  <div class="spacer spacer-sm"></div>

  <a href="#" class="btn btn-primary">Je m'inscris</a>
</div>
