---
title: teaser-profil
name: teaser-profil
collection: molecules
notes: |
  ##### Usage : `teaser-profil`
---
<div class="media teaser-profil">
  <div class="media-body">
    <h3 class="media-heading">Alberto Gomez</h3>
    <h5 class="media-heading"><a href="#">Spécialiste en stratégie digital</a></h5>
    <div class="icon-text icon-text-baseline icon-text-sm media-heading">
      <div class="icon" aria-hidden="true">
        <a href="#" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
      </div>
      <div class="text">
        <a href="#" class="no-underline" target="_blank">Linkedin</a>
      </div>
    </div>
  </div>
</div>
