---
title: teaser-degree
name: teaser-degree
collection: molecules
notes: |
  ##### Usage : `teaser-degree`
  ##### Options :
  - **degree** - object
---
<a href="#" class="teaser-degree no-underline d-block">
  <h4 class="teaser-degree-course media-heading">
    Nos formations continues&nbsp;<i class="fa fa-angle-right d-inline text-link m-l-05" aria-hidden="true"></i>
  </h4>
  <div class="spacer spacer-xs"></div>
  <div class="teaser-degree-infos">
    Etiam lobortis lacus leo. Maecenas euismod iaculis nisi id fringilla. Quisque ut ex leo. Morbi nec eleifend nunc, quis mattis orci. Aliquam sit amet nisi quis lectus pulvinar malesuada vitae nec diam. Fusce varius est odio, non imperdiet neque blandit in. Nunc ac augue in ipsum luctus auctor.
  </div>
</a>

