---
title: teaser-gallery
name: teaser-gallery
collection: molecules
notes: |
  ##### Usage : `teaser-gallery`
---
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <figure class="teaser-gallery" itemprop="associatedMedia">
        <img class="img-responsive" src="http://placehold.it/350x200" alt="">
        <div class="overlay">
           <a class="info" href="#">Zoom in</a>
        </div>
    </figure>
</div>
