---
title: teaser-timeline
name: teaser-timeline
collection: molecules
notes: |
---
<div class="row">
  <div class="col-xs-12 col-md-6">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div class="col-xs-12 col-md-6">
    <div class="text-danger">
      <i class="fa fa-info-circle" aria-hidden="true"></i>
      <span class="text-seance"><strong>SÉANCE D'INFORMATION: 31 AOÛT 2016</strong></span>
    </div>
    <div class="spacer spacer-sm"></div>
    <div class="btn btn-lg btn-primary">En savoir plus</div>
  </div>
</div>
