---
title: teaser-partner
name: teaser-partner
collection: molecules
notes: |
  ##### Usage : `teaser-partner`
---
<div class="teaser-partner text-center">
  <div class="partner-logo">
    <a href="#"><img class="img-responsive" src="/build/img/logo-polycom.png" alt=""></a>
  </div>
  <h3><a href="#" class="no-underline">Polycom</a></h3>
  <p class="fine-weight">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
</div>
