---
title: teaser-profil
name: teaser-profil
collection: molecules
notes: |
  ##### Usage : `teaser-profil`
---
<div class="media teaser-profil">
  <div class="media-left">
    <a href="#">
      <img class="media-object img-circle" src="/build/img/face-avatar.png" alt="Alberto Gomez">
    </a>
  </div>
  <div class="media-body">
    <h3 class="media-heading">Alberto Gomez</h3>
    <h5 class="media-heading">
      <a href="#" class="no-underline">Spécialiste en stratégie digital
        <i class="fa fa-angle-right text-link m-l-1" aria-hidden="true"></i>
      </a>
    </h5>
    <div class="icon-text icon-text-baseline icon-text-sm media-heading">
      <div class="icon" aria-hidden="true">
        <a href="#" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
      </div>
      <div class="text">
        <a href="#" class="no-underline" target="_blank">Linkedin</a>
      </div>
    </div>
  </div>
</div>
